Ессина Анастасия ФИТ 231
Mawak0/OOAiP pull request #7
Opened 2024-12-21 12:41 UTC by Mawak0

Реализована команда движения, ее регистрация, интерфейс ICommandInjectable и команда CommandInjectableCommand.

2024-12-24 10:45 UTC, zaryanezrya requested changes

2024-12-24 10:45 UTC, zaryanezrya commented on SpaceBattle.Lib/CommandInjectableCommand.cs
> +        if (_cmd.GetType() == typeof(EmptyCommand))
Вот так не надо.
Если положить в _cmd команду, которая будет выбрасывать исключение при выполнении, то удастся избавиться от этого if.
И не придётся тащить EmptyCommand, которая нужна для другого

2024-12-24 10:45 UTC, zaryanezrya commented on SpaceBattle.Lib/EmptyCommand.cs
Лишнее

2024-12-24 10:45 UTC, zaryanezrya commented on SpaceBattle.Lib/RegisterIoCDependencyMoveCommand.cs
> +        (object[] args) => new MoveCommand(Ioc.Resolve<IMoving>("Adapters.IMovingObject", args))).Execute();
Не массив args передаётся, а только нулевой элемент, где хранится объект, для которого нужно построить адаптер

2024-12-25 16:36 UTC, KryakPingvi approved these changes
окей, но есть сомнения

2024-12-25 16:36 UTC, KryakPingvi commented on SpaceBattle.Lib/Vector.cs
> +    public override int GetHashCode()
не уверен что здесь происходит

2024-12-25 16:56 UTC, zaryanezrya approved these changes

2025-02-17 06:12 UTC, merged